config/routes.rb
CVTCRideShare::Application.routes.draw do
  
  get "ride/book"
  devise_for :admins
  devise_for :users
  root :to => 'ride#search'
  
  resources :ride do
    collection do
      get 'search'
      get 'results'
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can [:edit, :update, :create], :all 
         cannot :delete, :all 
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
  
  # This is available to views
  helper_method :current_user

  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    # Use this to get nil instead of an error if not user exist
    @current_user ||= session[:current_user_id] && User.find_by_id(session[:current_user_id]) 
  end
  
  before_filter :configure_permitted_parameters, :configure_devise_params, if: :devise_controller?
  
  def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation) }
  end    
    
  def configure_devise_params

    registration_params = [:preferences, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
     
    rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end 

app/controllers/request_controller.rb
class RequestController < ApplicationController
  
  #cannot be used due to a nonworking book method 
  def accept
    @request = Request.find_by_token(params[:token])  
    @ride    = Request.ride
    
    #mark the request as confirmed and update the database
    @request.confirmed = true
    @ride.seats_booked += 1
    @request.save
    @ride.save
    
  end
  
end

app/controllers/ride_controller.rb
class RideController < ApplicationController
   before_filter :authenticate_user!, :only => [:show]
  
  def index
    @ride = Ride.all
  end

  def show
    @ride = Ride.find(params[:id])
    @markers = @ride.getStartEndCoordinates
  end

  def search
    
  end
  
  def book
    request.new
    @ride = Ride.find(params[:id])
    #currently book does not work. fake it
    ride_id = params[:id] ? params[:id] : 7
    
    #send the email after creating the record
    if RideRequestMailer.ride_request(ride_id, current_user.id).deliver
      flash[:notice] = 'A ride request email has been to the driver, you will be notified when accepted.'
    else
      flash[:notice] = 'An internal error occured, unable to send confirmation email.'
    end
  end
  
  def results
    @ride = Ride.search params
  end

  def new
    @ride = Ride.new  
  end
  
  def edit
    @ride = Ride.find(params[:id])
    if can? :edit, @rides && current_user == @ride.Driver_ID
      #count the amount of seats taken to set the lowest amount the user can set
      #this will be done when the requests table is made
      @minSeats = 0
      @maxSeats = @minSeats + 10
    else
      flash[:notice] = 'You do not have permissions to edit this ride.'
      redirect_to :action => 'show', :id => @ride
    end
  end
  
  def update
    @ride = Ride.find(params[:id])
    if @ride.update_attributes(ride_params)
      flash[:notice] = 'Ride was successfully updated.'
      redirect_to @ride
    else
      render :action => 'edit'
    end 
  end
  
  def create
    @ride = Ride.new(ride_params)
    @ride.Driver_ID = current_user
    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'New ride was successfully created.'}
        format.json { render action:'new', status: created, location: @ride}
      else
        format.html { render action: 'new' }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  #rails 4 way to do things
  def ride_params
    params.require(:ride).permit(:id, :Driver_ID, :Start_Address, :End_Address, :seat_count, :seats_booked, :price, :preferences, :Time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
end

app/helpers/request_helper.rb
module RequestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CVTCRideShare</title>
  <%= stylesheet_link_tag    "application","bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="container">
      <header>
        <h1>CVTC RideShare</h1>
      </header>
      <section class="nav">
        <nav> 
          <%=link_to "Home", root_url %> |
          <%=link_to "Ride Search", :controller=>"/ride", :action=>"search" %> |
          <% if can? :update, @rides %>
            <%=link_to "New Ride", :controller=>"/ride", :action=>"new" %> |
            <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %> |
            <%= link_to('Edit registration', edit_user_registration_path) %> |
          <% else %>
            <%= link_to('Login', new_user_session_path)  %> |
            <%= link_to('Register', new_user_registration_path)  %> |
          <% end %>
          <%=link_to "Book Ride", :controller=>"/ride", :action=>"book" %> |
        </nav>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>
      </section>
      <footer>
        A-Team Productions Copyright &copy; <%=Date.today.year %>
      </footer>
    </div>
  </body>
</html>

app/views/ride/book.html.erb
<h1>Book Ride</h1>
  <%= label_tag(:Start_Address) %>
  <%= text_field_tag(:Start_Address) %><br/>

  <%= label_tag(:End_Address) %>
  <%= text_field_tag(:End_Address) %><br/>

  <%= label_tag(:Time) %>
  <%= select_date nil, prompt: true, prefix: "Time" %><br/>

  <%= submit_tag("Submit") %>

app/views/ride/edit.html.erb
<h3>Edit Ride</h3>
<%= form_for @ride, url: {action: "update"} do|f| %>
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice]  %>
  </div>
<% end %>

<%= f.label :Start_Address %>
<%= f.text_field :Start_Address %><br/>

<%= f.label :End_Address %>
<%= f.text_field :End_Address %><br/>

<%= f.label :Time %>
<%= f.date_select :Time %><br/>

<%= f.label :seat_count %>
<%= f.select :seat_count, (@minSeats..@maxSeats).to_a %><br/>

<%= f.label :preferences %>
<%= f.text_area :preferences %><br/>

<%= f.label :price %>
<%= f.text_field :price %><br/>

<%= f.submit "Update" %>
<% end -%>

app/views/ride/results.html.erb
<h3>Results</h3>
<p>Your search found <%= @ride.length %> rides</p>
<table>
  <tr>
    <th>Start Address</th><th>End Address</th><th>Date</th><th>Seat</th><th>Preferences</th><th>Price</th>
  </tr>
<% @ride.each do |ride| %>
  <tr>
    <td><%= ride.Start_Address %></td> <td><%= ride.End_Address %></td> <td><%= ride.Time %></td>
    <td><%= ride.seat_count %></td> <td><%= ride.preferences %></td> <td><%= ride.price %></td>
<<<<<<< HEAD
    <% if can? :create, @rides && current_user == ride.Driver_ID %>
=======
    <td><%=link_to "Book", :controller=>"/ride", :action=>"book", :id=>"ride_id" %></td>

    <% if user_signed_in? && current_user.id == ride.Driver_ID %>
>>>>>>> e3fdefdcc6aa9e4937b5d02328517ab08bf9d72b
    <td><%= link_to "Edit", edit_ride_path(ride) %></td>
    <% end %>
  </tr>
<% end %>
</table>